import { DraftTask } from '../schemas/taskIntelligence';
import { calculateCosineSimilarity } from './embeddingService';
import { TASK_INTELLIGENCE_CONFIG } from '@/lib/config/taskIntelligence';

/**
 * Deduplicates P10 and P5 drafts based on embedding similarity
 *
 * Performance: O(n*m) where n = P10 count, m = P5 count
 * Expected: <100ms for typical case (3 P10 drafts × 2 P5 drafts = 6 comparisons)
 * Warning: May be slow if P10 or P5 count > 20 drafts
 *
 * @param p10Drafts - Drafts generated by Phase 10 (semantic gap filling)
 * @param p5Drafts - Drafts generated by Phase 5 (dependency gap filling)
 * @param similarityThreshold - Threshold for considering drafts similar (default: 0.85)
 * @returns Combined array with P10 drafts + P5 drafts that are not similar to any P10 draft
 */
export function deduplicateDrafts(
  p10Drafts: DraftTask[],
  p5Drafts: DraftTask[],
  similarityThreshold: number = TASK_INTELLIGENCE_CONFIG.EMBEDDING_SIMILARITY_THRESHOLD
): DraftTask[] {
  // Validate inputs
  if (!Array.isArray(p10Drafts) || !Array.isArray(p5Drafts)) {
    console.warn('[Deduplication] Invalid input arrays');
    return [];
  }

  const expectedDim = TASK_INTELLIGENCE_CONFIG.EMBEDDING_DIMENSIONS;

  // Check for null or malformed embeddings
  const validP10 = p10Drafts.filter(d => d.embedding && d.embedding.length === expectedDim);
  const validP5 = p5Drafts.filter(d => d.embedding && d.embedding.length === expectedDim);

  if (validP10.length !== p10Drafts.length) {
    console.warn(
      `[Deduplication] Filtered out ${p10Drafts.length - validP10.length} P10 drafts with invalid embeddings`
    );
  }
  if (validP5.length !== p5Drafts.length) {
    console.warn(
      `[Deduplication] Filtered out ${p5Drafts.length - validP5.length} P5 drafts with invalid embeddings`
    );
  }

  // Start with all valid P10 drafts (these take priority)
  const resultDrafts = [...validP10];

  // Process each valid P5 draft
  for (const p5Draft of validP5) {
    let isSimilarToAnyP10 = false;

    // Compare with each valid P10 draft
    for (const p10Draft of validP10) {
      const similarity = calculateCosineSimilarity(p5Draft.embedding, p10Draft.embedding);

      // If similarity exceeds threshold, consider it a duplicate
      if (similarity >= similarityThreshold) {
        isSimilarToAnyP10 = true;
        break;
      }
    }

    // If not similar to any P10 draft, add it to results
    if (!isSimilarToAnyP10) {
      resultDrafts.push(p5Draft);
    }
  }

  return resultDrafts;
}

/**
 * Calculates semantic similarity between two draft tasks using their embeddings
 * 
 * @param draft1 - First draft task
 * @param draft2 - Second draft task
 * @returns Cosine similarity score between 0 and 1
 */
export function calculateDraftSimilarity(draft1: DraftTask, draft2: DraftTask): number {
  return calculateCosineSimilarity(draft1.embedding, draft2.embedding);
}
