export const TASK_INTELLIGENCE_CONFIG = {
  QUALITY_EVAL_CHUNK_SIZE: 10,
  QUALITY_EVAL_CHUNK_DELAY_MS: 100,
  QUALITY_EVAL_RETRY_DELAY_MS: 2000,
  DRAFT_GENERATION_TIMEOUT_MS: 30_000,
  AI_RETRY_DELAY_MS: 2000,
  EMBEDDING_SIMILARITY_THRESHOLD: 0.85,
  EMBEDDING_DIMENSIONS: 1536,
} as const;

export type TaskIntelligenceConfig = typeof TASK_INTELLIGENCE_CONFIG;
