openapi: 3.0.3
info:
  title: Document Prioritization Status API
  version: 1.0.0
  description: API for retrieving document prioritization status and managing exclusions

paths:
  /api/documents/prioritization-status:
    get:
      summary: Get document prioritization status
      description: |
        Returns all documents with their task counts and prioritization status.
        Status is determined by comparing against the last prioritization baseline.
      parameters:
        - name: outcome_id
          in: query
          required: true
          schema:
            type: string
            format: uuid
          description: Active outcome ID for context
        - name: excluded_ids
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
              format: uuid
          style: form
          explode: false
          description: Comma-separated document IDs to mark as excluded
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 50
            maximum: 100
          description: Maximum documents to return
      responses:
        '200':
          description: Document status list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentStatusResponse'
              example:
                documents:
                  - id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                    name: "Product-roadmap-Q1.pdf"
                    task_count: 12
                    status: "included"
                    included_at: "2025-11-20T10:30:00.000Z"
                  - id: "b2c3d4e5-f6a7-8901-bcde-f12345678901"
                    name: "Customer-feedback.docx"
                    task_count: 8
                    status: "pending"
                    included_at: null
                  - id: "c3d4e5f6-a7b8-9012-cdef-123456789012"
                    name: "Old-brainstorm.pdf"
                    task_count: 6
                    status: "excluded"
                    included_at: "2025-11-15T08:00:00.000Z"
                summary:
                  included_count: 5
                  excluded_count: 2
                  pending_count: 2
                  total_task_count: 33
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "VALIDATION_ERROR"
                message: "outcome_id is required"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    DocumentStatus:
      type: object
      required:
        - id
        - name
        - task_count
        - status
      properties:
        id:
          type: string
          format: uuid
          description: Document ID (matches processed_documents.id)
        name:
          type: string
          description: Document filename
        task_count:
          type: integer
          minimum: 0
          description: Count of completed tasks from this document
        status:
          type: string
          enum:
            - included
            - excluded
            - pending
          description: |
            - included: Was in last prioritization baseline
            - excluded: User has toggled off
            - pending: New, not yet prioritized
        included_at:
          type: string
          format: date-time
          nullable: true
          description: When first included in baseline (null if never)

    DocumentStatusSummary:
      type: object
      required:
        - included_count
        - excluded_count
        - pending_count
        - total_task_count
      properties:
        included_count:
          type: integer
          minimum: 0
        excluded_count:
          type: integer
          minimum: 0
        pending_count:
          type: integer
          minimum: 0
        total_task_count:
          type: integer
          minimum: 0
          description: Sum of task_count across all non-excluded documents

    DocumentStatusResponse:
      type: object
      required:
        - documents
        - summary
      properties:
        documents:
          type: array
          items:
            $ref: '#/components/schemas/DocumentStatus'
        summary:
          $ref: '#/components/schemas/DocumentStatusSummary'

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          enum:
            - VALIDATION_ERROR
            - DATABASE_ERROR
            - INTERNAL_ERROR
        message:
          type: string
